### ISSUE TITLE
collect2: error: ld returned 1 exit status Makefile:1079: recipe for target 'logging_unittest' faile

### ISSUE THREAD

**Issue by jianhuaixie** [gflags/gflags#241] opened 2017-11-12 16:03 UTC
collect2: error: ld returned 1 exit status Makefile:1079: recipe for target 'logging_unittest' faile

**Comment by schuhschuh** [comment] 2017-12-12 00:07
Isn't this a duplicate of #240?

**Closed by schuhschuh** 2017-12-12 00:07 UTC
