### ISSUE TITLE
PVS Studio Analyzer Error V575 gflags.cc

### ISSUE THREAD

**Issue by drillsar** [gflags/gflags#219] opened 2017-07-09 07:52 UTC
I am getting the following error from PVS Studio Analyzer

V575 gflags.cc 556 The 'strncmp' function processes '0' elements. Inspect the third argument.

**Comment by schuhschuh** [comment] 2017-07-10 17:02
Thanks for reporting. I assume it's [line 594](https://github.com/gflags/gflags/blob/4a694e87361d08eff5c4c9e9f551b1a0d41f7c40/src/gflags.cc#L594) in case of the recent master HEAD. The `kRootDir` variable is indeed not used currently, so the condition will always be false. Haven't quite figured out the original intention of this code, and as long as it's not causing any harm left it in place. See also #86.

**Comment by schuhschuh** [comment] 2017-07-10 17:04
Closing this issue as kind of a duplicate of #86.

**Comment by schuhschuh** [comment] 2017-07-10 17:06
PS: If it's a problem to have a code analyzer report it as an error, please consider submitting a PR that silences the error/warning without changing the semantics of the code.

**Comment by tmccaff** [comment] 2017-07-11 00:11
@schuhscuh do you want me to make a pull request removing this error and document it todo krootdir or something like that?

**Comment by schuhschuh** [comment] 2017-07-11 08:47
Yes, I thought @drillsar was going to prepare one. But nevermind, I've created it myself just now.

@drillsar or @tmccaff could you please check out the `fix-219-strncmp-kRootDir-warning` (#222) branch and test if it resolves the error before I merge the change?

**Comment by drillsar** [comment] 2017-07-11 08:57
@schuhschuh I will check it later tnt..

**Comment by drillsar** [comment] 2017-07-11 11:25
It's fixed.

**Closed** 2017-07-11 11:26 UTC
Labels: 3 - done, other
