### ISSUE TITLE
googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>([...])'

### ISSUE THREAD

**Issue by jianhuaixie** [gflags/gflags#240] opened 2017-11-12 15:54 UTC
/usr/local/glog-0.3.5/src/googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
Makefile:1079: recipe for target 'logging_unittest' failed
make: *** [logging_unittest] Error 1

**Comment by uuudown** [comment] 2017-12-10 20:03
I think you should download gflags, compile and install. This works for me. I guess this is due to the different gcc version when compiling gflags and the one are building.

**Comment by uuudown** [comment] 2017-12-10 20:03
I mean download the source code of gflags to install. https://github.com/gflags/gflags

**Comment by schuhschuh** [comment] 2017-12-13 13:42
Closing this as duplicate of #203 (although your error appears to corresponds to an earlier revision where the `FlagRegisterer` constructor was not a template function).

**Closed by schuhschuh** 2017-12-13 13:42 UTC

**Comment by MirrorLakr** [comment] 2018-08-13 10:02
I download gflag from github to reinstall. But it doesn't work. So what should I do?
